support mutli-btye characters
laravel/prompts pull request #33
Opened 2023-08-03 01:33 UTC by tyler36

2023-08-03 02:06 UTC, jessarcher requested changes
Thanks!

Just tested on the text prompt, and the cursor position can get a bit broken. It seems to disappear at the end.

I think for anything to do with cursor position, we'd still want to use `mb_strlen` because an emoji, etc., should only count as one character in that scenario. I think it's just the padding where they should count as 2 characters.

2023-08-03 02:31 UTC, tyler36 commented
Thanks for the update. 

I revert the change for the "prompt" classes. So `mb_strwidth` is only applied to the theming files: ‘Renderer.php`, and `DrawsBoxes.php`.

Does that resolve the problem for you?

2023-08-03 05:28 UTC, jessarcher commented
The cursor issue seems fixed, but now it breaks when the characters exceed the terminal's width. I think it's a bit more complex than I'd hoped. We might need to go back to using `mb_strwidth` in more places, but then also use `mb_strimwidth` instead of `mb_substr`.

2023-08-03 08:42 UTC, crazywhalecc commented
I have previously written a program in PHP for terminal output of multi-byte text, it may need some special detection and calculation. In short, we may need a structure to mark the text input length, text display length and text data length. 😵‍💫 This is just my thoughts, I have not read all the prompts code.

2023-08-03 13:59 UTC, taylorotwell commented
@jessarcher just mark this as ready for review when ready.

2023-08-04 06:55 UTC, jessarcher commented
Hi @tyler36 and @crazywhalecc,

Can you please test the latest commit if you get a chance?

I ended up rewriting the virtual cursor and horizontal text scrolling logic, but it should be a lot easier to understand the next time I need to look at it.

2023-08-04 07:04 UTC, jessarcher approved these changes

2023-08-04 07:17 UTC, tyler36 commented
@jessarcher 

I ran through a quick test with 0c30f08f933521021243d93094326e717014482e

## Test: text

```
$name = text('楽しんでいますか？');
var_dump($name );
```

The box correctly grew and shrank with a mixutre of Japanese (hiragana and kanji) and English. 
`$name` correctly dumped.

![prompt-multibyte](https://github.com/laravel/prompts/assets/7234392/3ab5b004-140e-4724-a823-7b06125d1269)

Cursor behavior felt "normal" with extremely long Japanese lorem:
`$name` correctly dumped.
![prompt-ja-lorem](https://github.com/laravel/prompts/assets/7234392/1e7ee4ca-6c03-45aa-9c22-3350b0b90bea)

## Test: confirm

Confirm box also displayed correctly.

```php
$confirmed = confirm(
  label: '楽しんでいますか？',
  yes: 'はい',
  no: 'いいえ',
);
var_dump($confirmed);
```

See screenshot under screenshot above for comparison with extended "text" prompt.
`$confirmed` correctly dumped.

2023-08-04 07:19 UTC, tyler36 commented
Looks good to me. Thank you!

2023-08-04 15:02 UTC, merged

2023-08-04 15:02 UTC, taylorotwell commented
Thanks!